api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: applicationinsights-connection-string
        value: '{{ .Env.APPINSIGHTS_APPINSIGHTSCONNECTIONSTRING }}'
      - name: connectionstrings--openai
        value: '{{ .Env.OPENAI_CONNECTIONSTRING }}'
      - name: connectionstrings--sqldb
        value: Server=sql,1433;User ID=sa;Password={{ securedParameter "sql_password" }};TrustServerCertificate=true;Database=sqldb
      - name: connectionstrings--storagedocs
        value: '{{ .Env.STORAGE_BLOBENDPOINT }}'
  template:
    containers:
      - image: {{ .Image }}
        name: documentapi
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: services__description__http__0
            value: http://description.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: services__description__https__0
            value: https://description.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: services__markdown__http__0
            value: http://markdown.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: services__markdown__https__0
            value: https://markdown.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: services__vectorstore__http__0
            value: http://vectorstore.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: services__vectorstore__https__0
            value: https://vectorstore.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            secretRef: applicationinsights-connection-string
          - name: ConnectionStrings__openai
            secretRef: connectionstrings--openai
          - name: ConnectionStrings__sqldb
            secretRef: connectionstrings--sqldb
          - name: ConnectionStrings__storagedocs
            secretRef: connectionstrings--storagedocs
    scale:
      minReplicas: 1
tags:
  azd-service-name: documentapi
  aspire-resource-name: documentapi
